#!/usr/bin/env bash

terraform refresh \
  -var "key_name=terraform" \
  -var "public_key_path=$HOME/.ssh/terraform.pub" \
  -var "aws_access_key=$AWS_ACCESS_KEY_ID" \
  -var "aws_secret_key=$AWS_SECRET_ACCESS_KEY"

