#!/usr/bin/env bash

var=$(ssh-keygen -E md5 -lf ~/.ssh/terraform.pub | awk '{print $2}')
fingerprint=${var##MD5:}

token=$(terraform output -json 2>/dev/null | jq -r .discovery_token.value)
if [[ $token == '' ]]; then
  token=$(perl -e 'printf "%06x.%08x%08x\n", rand(0xffffff), rand(0xffffffff), rand(0xffffffff);')
  echo "Generated token: ${token}"
else
  echo "Reusing token: ${token}"
fi

terraform plan \
 -out "./digitalocean.tfplan" \
 -var "do_token=${DIGITALOCEAN_ACCESS_TOKEN}" \
 -var "pub_key=$HOME/.ssh/terraform.pub" \
 -var "pvt_key=$HOME/.ssh/terraform" \
 -var "ssh_fingerprint=${fingerprint}" \
 -var "discovery_token=${token}"

